### ISSUE TITLE
Allow users to enable both Word Wrap and Status Bar at once instead of only either one of them

### ISSUE THREAD

**Issue by win98se** [vxiiduu/NotepadEx#2]
Windows 10's Notepad already has this limitation removed.

**Comment by win98se** [comment]
Will reopen this issue once I have more information.

**Comment by vxiiduu** [comment]
This is not implemented in the original Notepad, because the line and column number displayed in the status bar will be incorrect (it will display the count of screen lines and not the count of actual lines in the file).
If/when I decide to get back into development I'll definitely have a look at whether it's possible to implement this.

**Comment by win98se** [comment]
Yes, this is also why I temporarily closed this issue for now. I'm currently drafting a list of feature inparity (compared to the Windows 10 version) for your reference.

**Comment by win98se** [comment]
> For your information, I'm also currently drafting a list of feature imparities (compared to the Windows 10 version) for your reference.

The list is now ready. I will create related issues separately.

---

**Feature Imparities and Bugs of vxiiduu's NotepadEx compared to Windows 10/11 (Classic) Notepad**

- [ ] Inability to enable both Word Wrap and Status Bar at once (because the line and column number displayed in the status bar will be incorrect)
  
  Details:
  https://github.com/vxiiduu/NotepadEx/blob/master/notepad/notepad.c#L2173
  When EM_LINEFROMCHAR is replaced with EM_FILELINEFROMCHAR, which the latter is documented by Microsoft as only available since Windows 10/Server Version 1809, it works properly on those platforms, but works abnormally on Windows 8.1 and below (Windows 10 Version 1507 to 1803 are not tested yet).

- [ ] When selecting text, the line and column number displayed in the status bar is based on start of the selection, instead of the current cursor position.

- [ ] The “Bush hid the facts” bugs exist.

  Details: https://en.wikipedia.org/wiki/Bush_hid_the_facts

- [ ] Does not support old Macs' CR line endings; Also does not respect registry values introduced in https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/.

- [ ] Does not support saving as UTF-8 without BOM; Also does not show the encoding in status bar; UTF-16 LE, UTF-16 BE and UTF-8 with BOM inaccurately shows as “Unicode”, “Unicode big endian” and “UTF-8” in Save As dialog respectively.

- [ ] Lack of New Window (Ctrl+Shift+N), Find Previous (Shift+F3) and Zoom (Ctrl+Plus, Ctrl+Minus and Ctrl+0) features.

- [ ] Lack of new keyboard shortcuts (Ctrl+Shift+S for Save As, and Ctrl+W for Close Current Window).

- [ ] Lack of the asterisk indicator in title bar when a file is modified.

- [ ] Missing “Input Values” Help link in Page Setup dialog.

  Details:
  It redirected to https://support.microsoft.com/en-us/windows/changing-header-and-footer-commands-in-notepad-c1b0e27b-497d-c478-c4c1-0da491cac148, but IMO it's better to make it show another dialog (that doesn't block accessing the previous dialog) including the whole content of that Help page.

- [ ] Missing “Wrap around” checkboxes in Find and Replace dialogs.

- [ ] Missing “Send Feedback” option in Help menu (Optional; Probably redirect to GitHub project's Issues tab?)

Also refer to https://docs.microsoft.com/en-us/windows-insider/archive/new-in-20h1#notepad-improvements-build-18963 (there are much more of them!).

**Comment by vxiiduu** [comment]
Thank you for the recommendations, I'm working on some of the features/changes you suggested. I have attached a testing version of NotepadEx if you want to try it, here -> [npex1220.zip](https://github.com/vxiiduu/NotepadEx/files/9374140/npex1220.zip)
Please keep in mind that this project is not trying to precisely copy Windows 10 notepad, just trying to port the most useful features back to Windows 7/Vista/XP/2000. The target feature-set is Windows 7 notepad with a few Windows 10 enhancements.

> * [ ]  Inability to enable both Word Wrap and Status Bar at once (because the line and column number displayed in the status bar will be incorrect)
>   Details:
>   https://github.com/vxiiduu/NotepadEx/blob/master/notepad/notepad.c#L2173
>   When EM_LINEFROMCHAR is replaced with EM_FILELINEFROMCHAR, which the latter is documented by Microsoft as only available since Windows 10/Server Version 1809, it works properly on those platforms, but works abnormally on Windows 8.1 and below (Windows 10 Version 1507 to 1803 are not tested yet).
Not surprising since the underlying code doesn't exist. I can probably hack something up to make this feature work, but it will take some more time to make something that has high performance.
> * [x]  When selecting text, the line and column number displayed in the status bar is based on start of the selection, instead of the current cursor position.
Fixed, will upload code shortly.
> * [x]  The “Bush hid the facts” bugs exist.
>   Details: https://en.wikipedia.org/wiki/Bush_hid_the_facts
Also fixed.
> * [ ]  Does not support old Macs' CR line endings; Also does not respect registry values introduced in https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/.
I don't think this is really very important. No systems are in any sort of common use which use this sort of line ending, I've never seen any such file in my whole life. Ever. If you happen to have a lot of files using old Mac line endings, feel free to send them to me, so I can use them for testing. It wouldn't be diifficult to add this feature.
> * [ ]  Does not support saving as UTF-8 without BOM; Also does not show the encoding in status bar; UTF-16 LE, UTF-16 BE and UTF-8 with BOM inaccurately shows as “Unicode”, “Unicode big endian” and “UTF-8” in Save As dialog respectively.
The terminology used here may be "inaccurate" but it's what has been in Windows for 15+ years. I don't see a reason to change it just to satisfy some pedantry.
> * [ ]  Lack of New Window (Ctrl+Shift+N), Find Previous (Shift+F3) and Zoom (Ctrl+Plus, Ctrl+Minus and Ctrl+0) features.
New window shortcut is a useless feature IMO. Just middle click on the notepad icon in the task bar
As for the others, they are useful, I will think about how to implement them.
> * [ ]  Lack of new keyboard shortcuts (Ctrl+Shift+S for Save As, and Ctrl+W for Close Current Window).
I will add Save As shortcut. As for Ctrl+W, I don't see the point in changing the default behavior, when Alt+F4 does exactly the same thing. You are free to use Autohotkey to add a Ctrl+W equivalent if you prefer it that way
> * [ ]  Lack of the asterisk indicator in title bar when a file is modified.
Added
> * [ ]  Missing “Input Values” Help link in Page Setup dialog.
>   Details:
>   It redirected to https://support.microsoft.com/en-us/windows/changing-header-and-footer-commands-in-notepad-c1b0e27b-497d-c478-c4c1-0da491cac148, but IMO it's better to make it show another dialog (that doesn't block accessing the previous dialog) including the whole content of that Help page.
In the stock Notepad Help file included with the operating system, all this information is already covered. Help->View Help
![image](https://user-images.githubusercontent.com/73044267/185404883-982c88a3-4f29-47fe-b014-2f8bc83118ff.png)

> * [ ]  Missing “Wrap around” checkboxes in Find and Replace dialogs.
I will consider this in the future, it is a useful feature.
> * [ ]  Missing “Send Feedback” option in Help menu (Optional; Probably redirect to GitHub project's Issues tab?)
Nah I think that's kind of dumb honestly, it's the kind of "windows 10 feature" I don't want to have.

**Comment by win98se** [comment]
Thank you for your hard work, but some small clarifications.

> The terminology used here may be "inaccurate" but it's what has been in Windows for 15+ years. I don't see a reason to change it just to satisfy some pedantry.

For this, it has been corrected in the latest versions of Windows 10/11 Notepad. Also UTF-8 text files without BOM is the mainstream.

> In the stock Notepad Help file included with the operating system, all this information is already covered. Help->View Help

Sadly this option redirects to https://support.microsoft.com/en-us/windows (that's right, the home page of Windows support website) on Windows 11, probably the same on Windows 10.

> It's the kind of "windows 10 feature" I don't want to have.

I agree, that's why I marked it as optional. :p

**Comment by vxiiduu** [comment]
I have added the ctrl+shift+S shortcut and released 1.2.2.0 with all the previous changes also.

I do intend to add some of the other features (e.g. wordwrap+statusbar) as well as making find and replace wrap around - I have personally been annoyed by a lack of this. But currently I am working on VxKex, so I haven't had much time.

Again, thank you for the feature recommendations.

**Comment by vxiiduu** [comment]
The latest release, 1.3.0.1 has introduced most of the features suggested in this issue.
